export default {
  HOME: 'Home',
  HEADER: 'Header',
  TIPS: 'Tips',
  TABS: 'Tabs',
  MYORDER: 'MyOrder',
  PROFILE: 'Profile',
  LOGIN: 'Login',
  REGISTER: 'Register',
  RESETPIN: 'ResetPin',
  PRIVACYPOLICY: 'PrivacyPolicy',
  REFUNDPOLICY: 'RefundPolicy',
  TERMSCONDITIONS: 'TermsConditions',
  ABOUT: 'About',
  PACKAGEDETAILS: 'PackageDetails',
  FEEDBACK: 'Feedback',
  DRAWERNAVIGATION: 'DrawerNavigation',
  EDITPROFILE: 'EditProfile',
  SLIDER: 'Slider',
  NOTIFICATION: 'Notification',
  SLIDERMAIN: 'SliderMain',
  SLIDERCUSTOM: 'SliderCustom',
};
